---
settings:
  name: StorageGRID
  release_notes_autogen:
    release_notes_repo: console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación de StorageGRID
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Qué hay de nuevo
      url: "/whats-new.html"
    - title: Problemas conocidos
      url: "/reference-known-issues.html"
  - title: Empezar
    entries:
    - title: Descubra los sistemas StorageGRID
      url: "/task-discover-storagegrid.html"
  - title: Administrar sistemas StorageGRID
    entries:
    - title: Visualice sus sistemas StorageGRID
      url: "/task-view-storagegrid.html"
    - title: Ver y actualizar certificados de StorageGRID
      url: "/task-manage-certificates.html"
    - title: Administrar StorageGRID mediante la vista avanzada
      url: task-administer-storagegrid.html
    - title: Utilice los servicios de datos de NetApp con StorageGRID
      url: "/task-enable-data-services.html"
    - title: Eliminar un sistema
      url: "/task-remove-storagegrid.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir asistencia
      url: "/task-support-registration.html"
    - title: Obtener ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
